### ISSUE TITLE
Fails to install with go1.20

### ISSUE THREAD

**Issue by schniggie** [projectdiscovery/httpx-action#5]
Hi guys,

as httpx requires go1.20, I updated the go version in the workflow, but it fails for me.

Workflow:
```
name: 💥 httpx - HTTP Web Server probing

on:
  push:
    paths:
    - 'naabu.log'
  workflow_dispatch:
  
jobs:
  httpx-scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: 💥 httpx - HTTP Web Server probing
        uses: projectdiscovery/httpx-action@main
        with:
          list: naabu.log

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: httpx.log
          path: httpx.log
```

And here is the error log after the workflow run:
```
Run projectdiscovery/httpx-action@main
  with:
    list: naabu.log
    output: httpx.log
    json: false
    random-ua: true
  env:
    GOROOT: /home/cd/actions-runner/_work/_tool/go/1.[2](https://github.com/schniggie/zecurity-vulnmgmt/actions/runs/5849360482/job/15857603192#step:4:2).2/x6[4](https://github.com/schniggie/zecurity-vulnmgmt/actions/runs/5849360482/job/15857603192#step:4:4)
Run [ ! -x /home/runner/go/bin/httpx ] && go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
  [ ! -x /home/runner/go/bin/httpx ] && go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
  [ ! -z "naabu.log" ] && echo "list=-l naabu.log" >> $GITHUB_ENV
  [ ! -z "httpx.log" ] && echo "output=-o httpx.log" >> $GITHUB_ENV || echo "output=-o httpx.log" >> $GITHUB_ENV
  [ ! -z "" ] && echo "flags=" >> $GITHUB_ENV
  false && echo "json=-json" >> $GITHUB_ENV
  true && echo "random-ua=-random-agent" >> $GITHUB_ENV
  echo "/home/runner/go/bin/" >> $GITHUB_PATH
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GOROOT: /home/cd/actions-runner/_work/_tool/go/1.2.2/x[6](https://github.com/schniggie/zecurity-vulnmgmt/actions/runs/5849360482/job/15857603192#step:4:6)4
can't load package: package github.com/projectdiscovery/httpx/cmd/httpx@latest: cannot find package "github.com/projectdiscovery/httpx/cmd/httpx@latest" in any of:
	/home/cd/actions-runner/_work/_tool/go/1.2.2/x64/src/pkg/github.com/projectdiscovery/httpx/cmd/httpx@latest (from $GOROOT)
	($GOPATH not set)
Error: Process completed with exit code 1.
```

Any idea?
